<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email yang Anda masukkan tidak terhubun_7920f6</name>
   <tag></tag>
   <elementGuidId>0d085616-5e4d-4473-b666-8ecd2a54d50e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email_container']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._9ay7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2743bf5-1bbf-4099-b717-b1008891ebbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9ay7</value>
      <webElementGuid>15d698f4-18a5-427c-b4b5-214847469cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.</value>
      <webElementGuid>f03aaf1d-8650-43b8-8da1-03ed2f1c996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_container&quot;)/div[@class=&quot;_9ay7&quot;]</value>
      <webElementGuid>d3188e64-8db1-40a0-863e-00342f1b47c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_container']/div[2]</value>
      <webElementGuid>303d570e-30ea-4db6-a202-e5e2632afaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login ke Facebook'])[1]/following::div[5]</value>
      <webElementGuid>b6c32bf4-56b7-4fa4-8277-140e0703e340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::div[7]</value>
      <webElementGuid>e5e68bc9-69d6-4bb3-8a97-7f5231bb32e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email yang Anda masukkan tidak terhubung ke akun.']/parent::*</value>
      <webElementGuid>1ac2683f-dd54-4a50-872f-e71040ce287b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
      <webElementGuid>403a69fd-bf01-42d0-ac17-867d25e088c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.' or . = 'Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.')]</value>
      <webElementGuid>4c336f80-6999-432e-b8d9-cf12f05525d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
